### ISSUE TITLE
Use language injection for Yul

### ISSUE THREAD

**Issue by nikitastupin** [JoranHonig/tree-sitter-solidity#15]
Hi @JoranHonig,

Thanks for the project! It can be used to improve Solidity syntax highlighting in Atom text editor which is great.

I've skimmed through your code and noticed that you've implemented Yul and Solidity languages at the same grammar. However tree-sitter has [language injection](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection) feature. It's designed to handle situations exactly like this one.

I suggest to split Yul and Solidity language implementations in order to increase maintainability of Solidity grammar and to make Yul grammar available on it's own. I'd like to help you with this task if you don't mind 😃 

Quick Google search showed that there is similar project [emilbayes/tree-sitter-yul](https://github.com/emilbayes/tree-sitter-yul). May be we can use some of it's parts.

**Comment by JoranHonig** [comment]
Long time no response 🙈 .

But sure, moving it out into a separate grammar seems like a good idea.

**Comment by JoranHonig** [comment]
I don't think we need to re-use anything really, just move existing parts out

**Comment by JoranHonig** [comment]
Splitting up the grammar would definitely be the best decision if syntax highlighting was the only usecase for this repository. 
 
Unfortunately it seems like splitting up the grammar wouldn't work in situations where we just parse a solidity file, because we'd skip over the yul bits


Happy to reopen this if I'm wrong!

**Comment by nikitastupin** [comment]
I didn't know it works this way. I'd think once tree-sitter is aware of an injected grammar it'd parse it too. Looks like it's not the case. If I find something new I'll let you know. Thank you!
