### ISSUE TITLE
README : Solidity Grammar 404 URL 

### ISSUE THREAD

**Issue by n3wborn** [JoranHonig/tree-sitter-solidity#16]
Hi ! 

Grammar can't be found at the [url](https://github.com/ethereum/solidity/blob/develop/docs/grammar/Solidity.g4) you give in README.md

Correct me if I'm wrong but now it seems there's 2 different links related to grammar in their doc

- [SolidityLexer.g4](https://github.com/ethereum/solidity/blame/develop/docs/grammar/SolidityLexer.g4)
- [SolidityParser.g4](https://github.com/ethereum/solidity/blame/develop/docs/grammar/SolidityParser.g4)

I think the good one is the second but I'm quite noob to all this (I've just found your repo reading about a  [nvim-treesitter solidity issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1168) and while reading your README I've found this dead link. 

If you can tell me which link is the *good one* between the two I can send a PR if you want. Thanks !

PS: Maybe a link to their [readthedocs-grammar-paragraph](https://docs.soliditylang.org/en/latest/grammar.html?#) could be a good idea too

**Comment by JoranHonig** [comment]
I added the links! Thanks for the issue report!
