### ISSUE TITLE
pragma experimental ABIEncoderV2;

### ISSUE THREAD

**Issue by seanyoung** [JoranHonig/tree-sitter-solidity#20]
The grammar does not permit this pragma:

```
pragma experimental ABIEncoderV2;
```

I wrote a fix for this, but then noticed that a fix for this is already on the [pragma branch](https://github.com/JoranHonig/tree-sitter-solidity/commit/ee5f3298ea165d06eb5d6765a535b6a57e16177d). Any reason why this has not been merged to master?

PS I'm expermenting with using tree-sitter-solidity for my solidity compiler project: https://github.com/hyperledger-labs/solang

**Comment by JoranHonig** [comment]
Closing this because I merged your pr 🚀
