### ISSUE TITLE
How to properly build .so file?

### ISSUE THREAD

**Issue by Malabarba** [JoranHonig/tree-sitter-solidity#31]
(Pinging @YongJieYongJie too)

First of all, thanks in advance for any help you can give me.
I have zero experience with rust, so forgive me if I'm asking something stupid.

I'm trying to be build an `.so` file that could be used by [emacs-tree-sitter](https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/87).

What I've done so far:
- installed cargo
- edited `Cargo.toml` to add the line `crate-type = ["cdylib"]` under `[lib]`
- ran `cargo build` from the project root

The outcome I get (amongst other things) is a `./target/debug/libtree_sitter_solidity.so` file, which I assumed was supposed to be the file I wanted. 
However, inspecting it with `nm` doesn't reveal the `tree_sitter_solidity` symbol to be exported (which I need).

I assume I'm doing something wrong here. Could someone point in the right direction?

**Comment by YongJieYongJie** [comment]
@Malabarba I would suggest trying the following:
1. Using [tree-sitter-cli](https://www.npmjs.com/package/tree-sitter-cli) for the compilation:
    - From this project root, run `tree-sitter generate`
    - Then run `tree-sitter test`
    - The `solidity.so` file would have been automatically re-compiled and placed at `~./tree-sitter/bin`
    - For details, see https://tree-sitter.github.io/tree-sitter/creating-parsers#command-generate
2. Use an earlier version of the tree-sitter-cli
    - I recall the emacs-tree-sitter requires an earlier version
    - My PR in the emacs-tree-sitter-langs repo should have taken that into consideration

**Comment by Malabarba** [comment]
Thank you! I had tried running `tree-sitter generate` before, but failed. Your suggestion to about the package version solved it.
Changing it to `"^0.19.1"` made it work.

Highlighting is working perfect now. 

While we're here... do you know if there's anywhere I can find indentation rules?
