### ISSUE TITLE
Add readable numbers notation

### ISSUE THREAD

**Issue by franfrandev** [JoranHonig/tree-sitter-solidity#35]
Hey, great work !

Just noticed that the ["readable numbers" notation](https://docs.soliditylang.org/en/v0.8.16/types.html#rational-and-integer-literals) is missing in the grammar and thus are not highlighted.

![Screenshot_2022-09-23_08-40-33](https://user-images.githubusercontent.com/51274081/191904999-69c52eb6-98e5-490f-83a2-ded339bbf9fc.png)

I could PR if you don't mind.

have a nice day

**Comment by JoranHonig** [comment]
I think this is fixed now!
