### ISSUE TITLE
Failing to parse "=" operators

### ISSUE THREAD

**Issue by CREESTL** [JoranHonig/tree-sitter-solidity#38]
As you can see on the picture down below, the `=` is not parsed as an operator, even thoug the `-` (at the end on the line) is parsed correctly (it's highlighted in rose)
 
 ![image](https://user-images.githubusercontent.com/37812120/211916992-7c1da8b0-09c0-4b17-85a0-52b284632951.png)

**Comment by JoranHonig** [comment]
Could this be an issue in nvim?
