### ISSUE TITLE
Function calls are not highlighted

### ISSUE THREAD

**Issue by zeroknots** [JoranHonig/tree-sitter-solidity#40]
Im using the solidity highlights.scm that comes with neovim's treesitter plugin.

unfortunately function calls are not highlighted for me at all.

What can I do to add that?

**Comment by PierrickGT** [comment]
@zeroknots if you run `:checkhealth nvim-treesitter`, is Solidity listed?

**Comment by mortimr** [comment]
Hey @PierrickGT , I'm seeing a similar issue

Basically most of the things I `:Inspect` give me `solcFuncBody` as a result, apart from keywords, builtin types and constants.
When running `:checkhealth nvim-treesitter` I can see solidity listed, and all my health checks are ok.

I tried both `:TSInstall solidity` and `:TSInstallFromGrammar solidity` and both seem to succeed.

Any idea on what might be the reason behind this behavior ?

**Comment by PierrickGT** [comment]
@mortimr what do you have in your Lua config?

I'm using [LazyVim](https://www.lazyvim.org/) which comes with TreeSitter and I only have this in my plugins config:
```
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "javascript",
        "json",
        "markdown",
        "solidity",
        "typescript",
      },
    },
  },
```

I'm also using [vscode-solidity-server](https://github.com/juanfranblanco/vscode-solidity) that you can easily configure using [Mason](https://github.com/williamboman/mason.nvim):
```
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "solhint",
        "vscode-solidity-server",
      },
    },
  },
```

**Comment by mortimr** [comment]
I've installed the plugin by running `:TSInstall solidity`, and I'm using the `nomicfoundation-solidity-language-server` language server (also tried to replace with yours but nothing changes)

**Comment by PierrickGT** [comment]
@mortimr and you've built your config from scratch?

Maybe you need to configure nvim-treesitter.
Here is the config from LazyVim: https://www.lazyvim.org/plugins/treesitter

**Comment by JoranHonig** [comment]
Hey all!

The neovim treesitter pkg's highlights queries are maintained in the nvim-treesitter repo: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/solidity/highlights.scm

I think the parser has all the features needed for successful highlighting 👍 

I'm closing this thread as it seems like this is more of a "nvim-treesitter" issue, lmk if this is not the case & I should reopen
