### ISSUE TITLE
Application to become a maintainer

### ISSUE THREAD

**Issue by Philogy** [JoranHonig/tree-sitter-solidity#45]
Hey @JoranHonig,

I'd love to actively contribute, merge issues and make tree-sitter up-to-date with Solidity 0.8 (custom types, custom operators, unchecked blocks, assembly memory-safe annotation). I personally and a lot of others rely on this parser quite a bit as it's the default Solidity parser/syntax highlighting provider for Neovim so I'd love to have the opportunity to actually fix it up!

I understand you might not have a lot of time to do everything yourself which is why I'm reaching out to lend a helping hand (I also tried to reach on Twitter but you some somewhat inactive there too).

Thanks!
\- Philogy

**Comment by plotchy** [comment]
Can vouch for Philogy's work ⭐️⭐️⭐️⭐️⭐️

**Comment by JoranHonig** [comment]
Yes please 🙌
