### ISSUE TITLE
Recursive mapping type results in an error

### ISSUE THREAD

**Issue by mateuszradomski** [JoranHonig/tree-sitter-solidity#46]
Hi,

The following code:

```solidity
mapping(uint256 x => mapping(uint256 y => bool isFinalized))
```

# Environment

I'm using [difftastic](https://github.com/Wilfred/difftastic) tool that sources this parser.
Used difftastic version is `Difftastic 0.55.0 (built with rustc 1.75.0)`

# Observed behaviour

When parsed results in the following errors:
```
m@mateuszs-mbp backend % difft --dump-ts test.sol | grep ERROR
  ERROR (0, 0) - (0, 60)
      ERROR (0, 16) - (0, 17)
        ERROR (0, 37) - (0, 38)
        ERROR (0, 42) - (0, 46)
```

# Expected behaviour

Does not error out and parses the type as a recursive mapping.

**Comment by JoranHonig** [comment]
fixed in https://github.com/JoranHonig/tree-sitter-solidity/pull/54

thanks for the report!
