### ISSUE TITLE
New release on npm/crates

### ISSUE THREAD

**Issue by ret2libc** [JoranHonig/tree-sitter-solidity#51]
Hi!

Would it be possible to have a new release on NPM (https://www.npmjs.com/package/tree-sitter-solidity) and on Crates.io (https://crates.io/crates/tree-sitter-solidity)? It seems the last version was uploaded 2 years ago.

Thanks a lot for the project!

**Comment by JoranHonig** [comment]
Done!

**Comment by ret2libc** [comment]
@JoranHonig Thanks a lot! Sorry I forgot to mention https://pypi.org/project/tree-sitter-solidity/ as well. If you could update it too it would be great ;)
