### ISSUE TITLE
Operator nodes broken

### ISSUE THREAD

**Issue by clason** [JoranHonig/tree-sitter-solidity#59]
The commit b5a23ead0f69d38b5c9a630f52f5c129132c16ed broke support for querying operators, in particular nvim-treesitter's 
```lisp
[
  "&&"
  "||"
  ">>"
  ">>>"
  "<<"
  "&"
  "^"
  "|"
  "+"
  "-"
  "*"
  "/"
  "%"
  "**"
  "="
  "<"
  "<="
  "=="
  "!="
  "!=="
  ">="
  ">"
  "!"
  "~"
  "-"
  "+"
  "++"
  "--"
  ":="
] @operator
```

I know that you are aware of this and that this is an upstream issue (which you've [already reported](https://github.com/tree-sitter/tree-sitter/issues/3331)), but would you consider reverting that (part of the) commit until this is fixed? The breakage is affecting our parser update tooling, requiring daily manual intervention. (I know that this is a "me" problem, but asking nicely never hurts.)

**EDIT:** I have disabled these captures for now to unbreak our CI. If and when this gets fixed, let me know and I'll re-enable them.

**Comment by JoranHonig** [comment]
rolled it back 👍 

found a better way of dealing with the issue
